name: Build and push Docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    env:
      BOT_USERNAME: ${{ secrets.MY_USERNAME }}
      BOT_PASSWORD: ${{ secrets.MY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker login
        run: echo ${BOT_PASSWORD} | docker login -u ${BOT_USERNAME} --password-stdin docker.pkg.github.com
      - name: Build and publish docker image
        run: |
          TAG=$(date +"%d.%m.%Y")
          docker build -f Dockerfile -t elena-test:$TAG .
          docker tag elena-test:$TAG docker.pkg.github.com/eleni-salamani/playground/elena-test:$TAG
          docker images
          docker push docker.pkg.github.com/eleni-salamani/playground/elena-test:$TAG

