name: On deployment event - trigger some action

on: [deployment]

jobs:
  check_deployment:
    name: deployment_created
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Test deployment details
        run: |
          echo "deployment id"
          echo "${{ github.event.deployment.id }}"
          echo "environment"
          echo "${{ github.event.deployment.environment }}"
