name: cd

on:
  pull_request:

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest

    steps:

    - name: pull code
      uses: actions/checkout@v1

    - name: Get list/paths of changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'

    - name: Parse changed files
      id: changeset
      run: echo ${{ steps.files.outputs.all }}

