name: ls-files

on:
  pull_request:
#    branches:
#      - master
#    types: [closed]

jobs:
  ls-files:
    name: ls-files
    runs-on: ubuntu-latest

#    if: github.event.pull_request.merged == true

    steps:
      - name: pull code
        uses: actions/checkout@v1

      - name:  Get list/paths of changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Get list/paths of changed files
#        id: files
#        uses: jitterbit/get-changed-files@v1
#        with:
#          format: 'json'
#
      - name: Parse changed files
        id: changeset
        run: |
          echo ${{ steps.files.outputs.all }}
          changes="'"${{ steps.files.outputs.all }}"'"
          echo "$changes"
          echo "$changes" | jq -c '.[]'
          for CHANGE in $(echo "$changes" | jq -c '.[]')
          do
          (
            echo "CHANGE IS $CHANGE"
            PATH=$(echo "$CHANGE" | xargs -n1 dirname)
            echo "PATH IS $PATH"
          )
          done
#          CHANGED_FILE=$(echo ${{ steps.files.outputs.all }})
#          UNIQUE=($(printf "%s\n" "${owner[@]}" | sort -u | tr '\n' ' '))

