name: Update image version in terraform on package release

on:
  registry_package:
    types: [published, updated]

jobs:
  release-dispatch:
    name:  release-dispatch
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.EL_B2B_BOT_TOKEN }}
      BOT_USERNAME: ${{ secrets.EL_B2B_BOT_USERNAME }}
      BOT_EMAIL: ${{ secrets.EL_B2B_BOT_EMAIL }}
      
    if: "!contains(github.event.registry_package.name, 'SNAPSHOT') && github.event.registry_package.package_type == 'docker'"

    steps:
      - name: get package information
        run: |
          echo "Published package: ${{ github.event.registry_package.name }}"
          echo "Published version: ${{ github.event.registry_package.package_version.version }}"
          echo "Package type: ${{ github.event.registry_package.package_type }}"
