name: "Tests on self-hosted runner - test"

on:
  schedule:
    - cron: 30 7 * * MON,TUE
    - cron: 0 8 * * MON

jobs:
  simple-tests:
    runs-on: [self-hosted, linux, x64, version1]
    steps:
      - uses: actions/checkout@v2
      - name: "Simple linux utilities"
        run: |
          hostname
          pwd
          ls -ltr
          node -v
          npm -v
          git version
          docker -v
          whoami
          newman -v
          cat /tmp/runner_details.txt
