name: "Tests on self-hosted runner - test"

on: [push]

jobs:
  simple-tests:
    runs-on: [self-hosted, linux, x64, version1]
    steps:
      - uses: actions/checkout@v2
      - name: "Simple linux utilities"
        run: |
          hostname
          pwd
          ls -ltr
          node -v
          npm -v
          git version
          docker -v
          whoami
          newman -v
          cat /tmp/log_text.txt
