name: On merge of release branches - trigger deployment

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  trigger_deployment:
    name: pr_merged
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      ENVIRONMENT: staging

    if: github.event.pull_request.merged == true

    steps:
      - name: Test env name has been set
        run: echo "${{ env.ENVIRONMENT }}"

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ env.GITHUB_TOKEN }}"
          environment: ${{ env.ENVIRONMENT }}
          
      - name: check deployment id
        run: echo "${{ steps.deployment.outputs.deployment_id }}"
